FORMAT: 1A

# HR Solution API

API pro produkt HR solution.

## Allowed HTTPs requests:

- `POST` - Creates or updates a resource
- `PUT` - Updates a resource
- `GET` - Retrieves a resource or list of resources
- `DELETE` - Delete a resource

## Typical Server Responses

- 200 `OK` - The request was successful (some API calls may return 201 instead).
- 201 `Created` - The request was successful and a resource was created.
- 204 `No Content` - The request was successful but there is no representation to return (that is, the response is empty).
- 400 `Bad Request` - The request could not be understood or was missing required parameters.
- 401 `Unauthorized` - Authentication failed or user does not have permissions for the requested operation.
- 403 `Forbidden` - Access denied.
- 404 `Not Found` - Resource was not found.
- 405 `Method Not Allowed` - Requested method is not supported for the specified resource.
- 429 `Too Many Requests` - Exceeded API limits. Pause requests, wait one minute, and try again.
- 503 `Service Unavailable` - The service is temporary unavailable. Try again later.

> Čas ve všech položkách (pokud není řečeno jinak) je unix_time plus ms (http://www.epochconverter.com).

# Group

Descrition.

## Resource [/url]

### Operation [POST]

Description.

#### Práce s token

+ Request (application/json)

    + Headers

            HEADER: value

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            {"response":"string"}

# Group Account

 Práce s účtem uživatele.

## Registrace uživatele [/account/registration]

### Operation [POST]

Description.

#### Registrace uživatele

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {
               "first_name": "first_name  last_name",
                "email": "email",
                "phone": "333 666 999",
                "login": "login_name",
                "password": "PASSWORD",
                "verify_password": "PASSWORD"
                
            }


+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            {
            "response":"Everything is ok",
            "registration":true
            }
 

+ Response 400 (application/json)

    + Headers

            Accept: application/json

    + Body

             {
             "response":"Something is not ok",
             "registration":false
             }
             
 
      
## Languages Collection [/language]

### Operation [GET]

Description.

#### List all Languages

+ Request (application/json)

    + Headers

              Access-Control-Allow-Origin: *
              

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
 
 
            [{
                "id": 1,
                "description": "Angličtina",
                "i18nKey": "en"
            },{
                 
                "id": 2,
                 "description": "Čeština",
                "i18nKey": "cs"
            }] 
            
## Countries Collection [/country]

### Operation [GET]

Description.

#### List all Countries

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
             

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
            
            [{
                "id": 1,
                "description": "USA",
                "i18nKey": "US"
            },{
                 
                "id": 2,
                 "description": "Canada",
                "i18nKey": "CA"
            }]
            
## User detail [/account/{id}]

### Operation [GET]

Description.

#### User detail

+ Request (application/json)
    + Headers

             Access-Control-Allow-Origin: *


+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
            
            {
                "name_surname": "John Doe",
                "email": "johndoe@email.cz",
                "phone": "+420 111 333 555",
                "company": "Example Company",
                "street": "Sadová",
                "city": "Ostrava",
                "zip": "702 00",
                "country": "Czech Rep",
                "vat_id": "112233"
            }

## User update [/account]

### Operation [PUT]

Description.

#### User detail

+ Request (application/json)
    + Headers

             Access-Control-Allow-Origin: *
             
    + Body
    
            {
                "name_surname": "name  surname",
                "email": "email",
                "phone": "phone",
                "company": "company",
                "street": "street",
                "city": "city",
                "zip": "zip",
                "country": "country",
                "vat_id": "vat_id"
                
            }


+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
    
            {
             "response":"User account updated."
            }

+ Response 400 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
    
            {
             "response":"An error occured."
            }

            
## Recovery password [/account/recoverpassword]
### I need new password [POST]

Obdrzi jeden email na nemz bylo zapomenuto heslo.
Vyhleda uzivatele podle tohoto emailu, vytvori identifikacni kod a odesle email s odkazem na zmenu hesla ktery obsahuje identifikacni kod.
Pokud zadany email neexistuje nic neprovadi.
Vzdy vraci 204, aby nebylo mozne zjistovat existenci emailu v systemu.

url v emailu pro zmenu hesla je [ /passwordrecovery/newpassword?email=XXX&code=XXX ]
kde email je email pro doplneni do login page, na kterou se presmeruje po uspesne zmene hesla
a code je dlouhy retezec pro identifikaci uzivatele

+ Request

        {
            "email": "email@example.com"
        }

+ Response 204


## Users 401 messages [/test/messages]
### Users 401 messages [GET]
            
+ Response 401 (Unauthorized)

    + Header
    
            Access-Control-Allow-Origin: *
            
    + Body
    
            {
                "messages": [
                    {"i18nKey":"i18nKeyErrorMessageUnauthorized1","type":"error"},
                    {"i18nKey":"i18nKeyErrorMessageUnauthorized2","type":"error"},
                    {"i18nKey":"i18nKeyErrorMessageUnauthorized3","type":"error"}
                ]
            }                        
            
## Users Login [/account/login]
### Login User [POST]

+ Response 200 (application/json)

    + Header
            
            Access-Control-Allow-Origin: *
            
    + Body
            
            {
            "user_id": 12312334,
            "token": "security_token",
            "role":["admin","user","consultant","businessman"],
            "license":["hr1","hr2","hr3","hr4","hr5"],
            "name_surname":"John Black"
            }
            
## Users 201 message [/test/messages201]
### Users 201 message [GET]
            
+ Response 201 

    + Header
    
            Access-Control-Allow-Origin: *
            X-License-Hr4: false
            Access-Control-Expose-Headers: X-License-Hr4
            
    + Body
    
            {
                "messages": 
                    {"i18nKey":"i18nKeyCreatedMessage","type":"success"}
            } 
            
## Orders Collection [/account/{id}/orders]
### Operation [GET]
Description.

#### List all user orders

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            [{
            "id": 1,
            "name": "Databáze lidských zdrojů",
            "insert_time": "1.11.2014",
            "valid_until": "1.1.2015",
            "status": "WAITING"
            },{
            "id": 2,
            "name": "Správný dílek do týmu",
            "insert_time": "16.10.2014",
            "valid_until": "1.1.2015",
            "status": "INVOICE"
            },{
            "id": 3,
            "name": "Zapracování",
            "insert_time": "16.10.2014",
            "valid_until": "16.12.2014",
            "status": "PAID"
            }]
            
### Operation [POST]
Create a new license orders

#### Save new license order

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    + Body

            {
                "invoice_items": {
                    "name": 3   
                },
                "modules":[{
                    "module_id":1,
                    "license_id":1,
                    "training":[1,2],
                    "consult_hours":5
                    },
                    {
                    "module_id":2,
                    "license_id":1,
                    "training":[3,4],
                    "consult_hours":0
                    }]
            }

+ Response 201 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            {
                "messages": [
                {"i18nKey":"i18nKeySuccessMessageNewOrderCreated","type":"success"}
                ]
            }    
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageNewOrderNotCreated","type":"error"}
                 ]
            }   
            
## User's password change [/account/passwordchange]
### Operation [POST]
Description.

#### Store a changed user password

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

             Access-Control-Allow-Origin: *

    + Body
             
            {
                "messages": [
                    {"i18nKey":"i18nKeySuccessMessagePasswordChange","type":"success"}
                ]
            }
             
+ Response 400 (application/json)

    + Headers

            Accept: application/json

    + Body

             {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessagePasswordChange","type":"error"}
                 ]
            }
            

## Download pdf [/order/{id}/invoice]
### Download [GET]

+ Response 200

    + Header

            Content-Type: application/pdf
            Content-Disposition: attachment; filename="invoice.pdf"
            Access-Control-Allow-Origin: *

    + Body

            Order invoice

## Person detail [/account/{user_id}/hr4/person/{person_id}]

### Operation [GET]

Description.

#### Show Person detail

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
             

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
             X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body
            
            {
            "person_name": "Person name",
            "person_surname": "Person surname" ,
            "person_email":"person@seznam.cz",
            "person_position":"Boss"
            }
            
            
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            [{
                 "messages":  
                    {"i18nKey":"i18nKeyErrorMessagePersonDetail","type":"error"}
                  
            }]
            
            
### Operation [PUT]

Description.

#### Save Person detail

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
             
    + Body
            
            {
            "person_name": "Person name",
            "person_surname": "Person surname" ,
            "person_email":"person@seznam.cz",
            "person_position":"Boss"
            }

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body
             
            [{
                 "messages":  
                    {"i18nKey":"i18nKeySuccessMessagePersonDetailUpdate","type":"success"}
                  
            }]    
            
            
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            [{
                 "messages":  
                    {"i18nKey":"i18nKeyErrorMessagePersonDetail","type":"error"}
                  
            }]           
            
### Operation [POST]

Description.

#### Delete Person

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
             
     

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            Accept: application/json
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body
            
            [{
                 "messages": 
                    {"i18nKey":"i18nKeySuccessMessagePersonDetailDeleted","type":"success"}
                  
            }]    
            
            
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            [{
                 "messages": 
                    {"i18nKey":"i18nKeyErrorMessagePersonDetail","type":"error"}
                  
            }]           
            
            
            
## Recovery password [/account/recoverynewpassword]
### new password [POST]

request to set user's password
code - long string to recognize user
password - new password for user

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {
                "code": "CODE",
                "password": "PASSWORD"
            }
            
+ Response 200

    + Body
    
            {
                "messages": {
                                "i18nKey": "passwordRecoveryNewPasswordSuccess",
                                "type": "success"
                            }
            }

+ Response 400

## Users 402 Payment Required [/test/messages402]
### Users 402 Payment Required [GET]
            
+ Response 402

    + Header
    
            Access-Control-Allow-Origin: *
            
    + Body
    
            {
                "data": "data"
            }
            
## HR4 person list [/account/{id}/hr4/persons]
### Operation [GET]
Get the list of persons for hr4 model and specific user.

#### List all persons

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            [{
            "id": 1,
            "name": "František",
            "surname": "Vomáčka",
            "position": "Kuchař",
            "diagnostic_time":"1412154655000"
            },{
            "id": 2,
            "name": "Elizabeth II.",
            "surname": "Windsor",
            "position": "Queen of the Empire",
            "diagnostic_time":null
            },{
            "id": 3,
            "name": "Silvestr",
            "surname": "Alone",
            "position": "Boxer",
            "diagnostic_time":"1406884255000"
            },{
            "id": 4,
            "name": "Arnold",
            "surname": "Schwarz",
            "position": "Krotitel predátorů",
            "diagnostic_time":null
            },{
            "id": 5,
            "name": "Elton",
            "surname": "John",
            "position": "Profesionální účastník karaoke",
            "diagnostic_time":"1409562655000"
            }]
            
            
## HR4 person results [/account/{id}/hr4/person/{id_person}/{id_result}]

### Operation [GET]
Get the list of person's results for hr4 model and specific user.

#### List person's results

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            [{
            "result_id": 1,
            "result_date": "6.2.2014",
            "result_diagnosticurl": "http://scanner.forHrsolution.cz?code=255662",
            "status": "LICENCE"
            },{
            "result_id": 2,
            "result_date": "6.3.2014",
            "result_diagnosticurl": "http://scanner.forHrsolution.cz?code=255662",
            "status": "NORESULT"
            },{
            "result_id": 3,
            "result_date": "24.7.2014",
            "result_diagnosticurl": "http://scanner.forHrsolution.cz?code=255662",
            "status": "NOLICENCE"
            },{
            "result_id": 4,
            "result_date": "16.11.2014",
            "result_diagnosticurl": "http://scanner.forHrsolution.cz?code=255662",
            "status": "PAIDLICENCE"
            }]
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessagePersonDetail","type":"error"}
                 ]
            }           
            
### Operation [POST]
Share person's result

#### Share person's result

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    + Body

             {
                "EmailsToShare": "person@seznam.cz,person@seznam.cz,person@seznam.cz"
                 
            }

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                "messages": [
                {"i18nKey":"i18nKeySuccessMessagePersonDetailShare","type":"success"}
                ]
            }    
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessagePersonDetailShare","type":"error"}
                 ]
            }    
            
### Operation [PUT]
Send email for diagnostic to the person

#### Send email whith scaner url

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    + Body

             {
                "person_email": "person@seznam.cz"
                 
            }

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                "messages": [
                {"i18nKey":"i18nKeySuccessMessagePersonDetailDiagnosticEmail","type":"success"}
                 ] 
            }    
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessagePersonDetailDiagnosticEmail","type":"error"}
                  ] 
            }           
              
### Operation [DELETE]
Delete result of person

#### Delete result of person

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                "messages":[  
                {"i18nKey":"i18nKeySuccessMessagePersonDetailDeleteResult","type":"success"}
                 ]
            }    
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages":[  
                    {"i18nKey":"i18nKeyErrorMessagePersonDetailDeleteResult","type":"error"}
                  ]
            }           
                  
                  
                  
## HR4 New Consultation [/account/{id}/hr4/newconsultation]

### Operation [GET]
Get New Consultation details for hr4 model.

#### New Consultation details

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
            "consultationForms": [ 
             {"title":"Telefon","code":"PHONE"},
             {"title":"Osobně v DAP Services","code":"INPERSONDAPS"},
             {"title":"Osobně u nás","code":"INPERSON"}
 
             ],
             "consultationLenght":"30 min",
             "description":"hr4_new_consultation_diagnostic_description_Text"
             }
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageNewConsultation","type":"error"}
                 ]
            }           
            
### Operation [POST]
Share person's result

#### Order New Consultation

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    + Body

             {
                "person_id": "23",
                "result_id": "23455",
                "user_id": "12",
                "consultation_date": "12.11.20014 13:30",
                "consultation_form": "INPERSONDAPS",
                "consultation_Lenght": "30 min"
                 
            }

+ Response 201 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                "messages": [
                {"i18nKey":"i18nKeySuccessMessageNewConsultationCreated","type":"success"}
                ]
            }    
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageNewConsultationNotCreated","type":"error"}
                 ]
            }   
            
## Get module license configuration [/account/{id}/order/module/{id_module}]

### Operation [GET]
Get the list of possible licences for module

#### List person's results

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    + Body

            [
                {
                  "type": 1,
                  "resource_name":"order_module_license_type_half_year_license",
                  "price": 100,
                  "consultation_hours": 3,
                  "consultation_hour_price": 5,
                  "valid_until":1449229755000,
                  "training": [
                    {
                      "id": 1,
                      "training_name":"module_training_1",
                      "price": 15,
                      "required": false
                    },
                    {
                      "id": 2,
                      "training_name":"module_training_2",
                      "price": 25,
                      "required": false
                    },
                    {
                      "id": 3,
                      "training_name":"module_training_3",
                      "price": 12,
                      "required": false
                    },
                    {
                      "id": 4,
                      "training_name":"module_training_4",
                      "price": 10,
                      "required": false
                    },
                    {
                      "id": 5,
                      "training_name":"module_training_5",
                      "price": 5,
                      "required": true
                    }
                  ]
                },
                {
                  "type": 2,
                  "resource_name":"order_module_license_type_single_license",
                  "price": 4,
                  "consultation_hours": 1,
                  "consultation_hour_price": 10,
                  "training": [
                    {
                      "id": 1,
                      "training_name":"module_training_1",
                      "price": 17,
                      "required": false
                    },
                    {
                      "id": 2,
                      "training_name":"module_training_2",
                      "price": 30,
                      "required": false
                    },
                    {
                      "id": 5,
                      "training_name":"module_training_5",
                      "price": 10,
                      "required": true
                    }
                  ]
                }
              ]

+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageModuleLicense","type":"error"}
                 ]
            }     

# Group Person

Page for create new persons and diagnostic (/hr4/newPersons)

## generate new diagnostic url [/account/{id}/hr4/persons/getNewDiagnosticUrl]

### Operation [GET]

Return unique url of diagnostic, API must manage all generated url create, delete, ...

#### Generating diagnostic url

+ Request

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
    
            {
                "diagnosticUrl": "https://www.some.new/url/for/diagnostic"
            }

## create new persons with new diagnostics [/account/{id}/hr4/persons/create]

### Operation [POST]

Create new persons, create new diagnostics for each person and check if diagnostics urls is unique. Sends email to selected persons.
If checking diagnostic url fail it return some 40X to show error message or page with message to contact admin.

#### complete creating new persons

+ Request (application/json)

    + Headers
    
            Access-Control-Allow-Origin: *

    + Body

            {
                "words": ["Me", "Work", "Missile", "Grandmother"],
                "persons": [
                    {
                        "firstName": "Karl",
                        "lastName": "Schlanshamer",
                        "email": "karlAusDeutchland@germany.de",
                        "diagnosticUrl": "https://www.some.new/url/for/diagnostic/6asd56a4f"
                    },{
                        "firstName": "Sergei",
                        "lastName": "Dimitrienko",
                        "email": "dinitriSergei@motherrussia.ru",
                        "diagnosticUrl": "https://www.some.new/url/for/diagnostic/asf3w4687"
                    }
                ]
            }

+ Response 200  (application/json)

    + Headers
    
            Access-Control-Allow-Origin: *
    
    + Body
    
            {
                 "messages": [
                    {"i18nKey":"hr4_new_person_submit_successful","type":"success"}
                 ]
            }
    
+ Response 400  (application/json)
    
    + Headers
    
            Access-Control-Allow-Origin: *

## Countries Collection [/country/en]
### List all Countries [GET]
+ Response 200 (application/json)

    + Header

            Accept: application/json

    + Body

                [{"id":1,"code":"AF","name":"Afghanistan"},
                {"id":2,"code":"AX","name":"Åland Islands"},
                {"id":3,"code":"AL","name":"Albania"},
                {"id":4,"code":"DZ","name":"Algeria"},
                {"id":5,"code":"AS","name":"American Samoa"},
                {"id":6,"code":"AD","name":"Andorra"},
                {"id":7,"code":"AO","name":"Angola"},
                {"id":8,"code":"AI","name":"Anguilla"},
                {"id":9,"code":"AQ","name":"Antarctica"},
                {"id":10,"code":"AG","name":"Antigua and Barbuda"},
                {"id":11,"code":"AR","name":"Argentina"},
                {"id":12,"code":"AM","name":"Armenia"},
                {"id":13,"code":"AW","name":"Aruba"},
                {"id":14,"code":"AU","name":"Australia"},
                {"id":15,"code":"AT","name":"Austria"},
                {"id":16,"code":"AZ","name":"Azerbaijan"},
                {"id":17,"code":"BS","name":"Bahamas"},
                {"id":18,"code":"BH","name":"Bahrain"},
                {"id":19,"code":"BD","name":"Bangladesh"},
                {"id":20,"code":"BB","name":"Barbados"},
                {"id":21,"code":"BY","name":"Belarus"},
                {"id":22,"code":"BE","name":"Belgium"},
                {"id":23,"code":"BZ","name":"Belize"},
                {"id":24,"code":"BJ","name":"Benin"},
                {"id":25,"code":"BM","name":"Bermuda"},
                {"id":26,"code":"BT","name":"Bhutan"},
                {"id":27,"code":"BO","name":"Bolivia"},
                {"id":28,"code":"BQ","name":"Bonaire"},
                {"id":29,"code":"BA","name":"Bosnia and Herzegovina"},
                {"id":30,"code":"BW","name":"Botswana"},
                {"id":31,"code":"BV","name":"Bouvet Island"},
                {"id":32,"code":"BR","name":"Brazil"},
                {"id":33,"code":"IO","name":"British indian ocean territory"},
                {"id":34,"code":"BN","name":"Brunei Darussalam"},
                {"id":35,"code":"BG","name":"Bulgaria"},
                {"id":36,"code":"BF","name":"Burkina Faso"},
                {"id":37,"code":"BI","name":"Burundi"},
                {"id":38,"code":"KH","name":"Cambodia"},
                {"id":39,"code":"CM","name":"Cameroon"},
                {"id":40,"code":"CA","name":"Canada"},
                {"id":41,"code":"CV","name":"Cape Verde"},
                {"id":42,"code":"KY","name":"Cayman Islands"},
                {"id":43,"code":"CF","name":"Central African Republic"},
                {"id":44,"code":"TD","name":"Chad"},
                {"id":45,"code":"CL","name":"Chile"},
                {"id":46,"code":"CN","name":"China"},
                {"id":47,"code":"CX","name":"Christmas Island"},
                {"id":48,"code":"CC","name":"Cocos (keeling) Islands"},
                {"id":49,"code":"CO","name":"Colombia"},
                {"id":50,"code":"KM","name":"Comoros"},
                {"id":51,"code":"CG","name":"Congo"},
                {"id":52,"code":"CD","name":"Congo"},
                {"id":53,"code":"CK","name":"Cook Islands"},
                {"id":54,"code":"CR","name":"Costa Uica"},
                {"id":55,"code":"CI","name":"Côte d'ivoire"},
                {"id":56,"code":"HR","name":"Croatia"},
                {"id":57,"code":"CU","name":"Cuba"},
                {"id":58,"code":"CW","name":"Curaçao"},
                {"id":59,"code":"CY","name":"Cyprus"},
                {"id":60,"code":"CZ","name":"Czech Republic"},
                {"id":61,"code":"DK","name":"Denmark"},
                {"id":62,"code":"DJ","name":"Djibouti"},
                {"id":63,"code":"DM","name":"Dominica"},
                {"id":64,"code":"DO","name":"Dominican Republic"},
                {"id":65,"code":"EC","name":"Ecuador"},
                {"id":66,"code":"EG","name":"Egypt"},
                {"id":67,"code":"SV","name":"El Salvador"},
                {"id":68,"code":"GQ","name":"Equatorial Guinea"},
                {"id":69,"code":"ER","name":"Eritrea"},
                {"id":70,"code":"EE","name":"Estonia"},
                {"id":71,"code":"ET","name":"Ethiopia"},
                {"id":72,"code":"FK","name":"Falkland Islands"},
                {"id":73,"code":"FO","name":"Faroe Islands"},
                {"id":74,"code":"FJ","name":"Fiji"},
                {"id":75,"code":"FI","name":"Finland"},
                {"id":76,"code":"FR","name":"France"},
                {"id":77,"code":"GF","name":"French Guiana"},
                {"id":78,"code":"PF","name":"French Polynesia"},
                {"id":79,"code":"TF","name":"French Southern Territories"},
                {"id":80,"code":"GA","name":"Gabon"},
                {"id":81,"code":"GM","name":"Gambia"},
                {"id":82,"code":"GE","name":"Georgia"},
                {"id":83,"code":"DE","name":"Germany"},
                {"id":84,"code":"GH","name":"Ghana"},
                {"id":85,"code":"GI","name":"Gibraltar"},
                {"id":86,"code":"GR","name":"Greece"},
                {"id":87,"code":"GL","name":"Greenland"},
                {"id":88,"code":"GD","name":"Grenada"},
                {"id":89,"code":"GP","name":"Guadeloupe"},
                {"id":90,"code":"GU","name":"Guam"},
                {"id":91,"code":"GT","name":"Guatemala"},
                {"id":92,"code":"GG","name":"Guernsey"},
                {"id":93,"code":"GN","name":"Guinea"},
                {"id":94,"code":"GW","name":"Guinea-bissau"},
                {"id":95,"code":"GY","name":"Guyana"},
                {"id":96,"code":"HT","name":"Haiti"},
                {"id":97,"code":"HM","name":"Heard Island and Mcdonald Islands"},
                {"id":98,"code":"VA","name":"Holy see (vatican city state)"},
                {"id":99,"code":"HN","name":"Honduras"},
                {"id":100,"code":"HK","name":"Hong Kong"},
                {"id":101,"code":"HU","name":"Hungary"},
                {"id":102,"code":"IS","name":"Iceland"},
                {"id":103,"code":"IN","name":"India"},
                {"id":104,"code":"ID","name":"Indonesia"},
                {"id":105,"code":"IR","name":"Iran"},
                {"id":106,"code":"IQ","name":"Iraq"},
                {"id":107,"code":"IE","name":"Ireland"},
                {"id":108,"code":"IM","name":"Isle of man"},
                {"id":109,"code":"IL","name":"Israel"},
                {"id":110,"code":"IT","name":"Italy"},
                {"id":111,"code":"JM","name":"Jamaica"},
                {"id":112,"code":"JP","name":"Japan"},
                {"id":113,"code":"JE","name":"Jersey"},
                {"id":114,"code":"JO","name":"Jordan"},
                {"id":115,"code":"KZ","name":"Kazakhstan"},
                {"id":116,"code":"KE","name":"Kenya"},
                {"id":117,"code":"KI","name":"Kiribati"},
                {"id":118,"code":"KP","name":"Korea"},
                {"id":119,"code":"KR","name":"Korea"},
                {"id":120,"code":"KW","name":"Kuwait"},
                {"id":121,"code":"KG","name":"Kyrgyzstan"},
                {"id":122,"code":"LA","name":"Lao People's Democratic Republic"},
                {"id":123,"code":"LV","name":"Latvia"},
                {"id":124,"code":"LB","name":"Lebanon"},
                {"id":125,"code":"LS","name":"Lesotho"},
                {"id":126,"code":"LR","name":"Liberia"},
                {"id":127,"code":"LY","name":"Libya"},
                {"id":128,"code":"LI","name":"Liechtenstein"},
                {"id":129,"code":"LT","name":"Lithuania"},
                {"id":130,"code":"LU","name":"Luxembourg"},
                {"id":131,"code":"MO","name":"Macao"},
                {"id":132,"code":"MK","name":"Macedonia"},
                {"id":133,"code":"MG","name":"Madagascar"},
                {"id":134,"code":"MW","name":"Malawi"},
                {"id":135,"code":"MY","name":"Malaysia"},
                {"id":136,"code":"MV","name":"Maldives"},
                {"id":137,"code":"ML","name":"Mali"},
                {"id":138,"code":"MT","name":"Malta"},
                {"id":139,"code":"MH","name":"Marshall Islands"},
                {"id":140,"code":"MQ","name":"Martinique"},
                {"id":141,"code":"MR","name":"Mauritania"},
                {"id":142,"code":"MU","name":"Mauritius"},
                {"id":143,"code":"YT","name":"Mayotte"},
                {"id":144,"code":"MX","name":"Mexico"},
                {"id":145,"code":"FM","name":"Micronesia"},
                {"id":146,"code":"MD","name":"Moldova"},
                {"id":147,"code":"MC","name":"Monaco"},
                {"id":148,"code":"MN","name":"Mongolia"},
                {"id":149,"code":"ME","name":"Montenegro"},
                {"id":150,"code":"MS","name":"Montserrat"},
                {"id":151,"code":"MA","name":"Morocco"},
                {"id":152,"code":"MZ","name":"Mozambique"},
                {"id":153,"code":"MM","name":"Myanmar"},
                {"id":154,"code":"NA","name":"Namibia"},
                {"id":155,"code":"NR","name":"Nauru"},
                {"id":156,"code":"NP","name":"Nepal"},
                {"id":157,"code":"NL","name":"Netherlands"},
                {"id":158,"code":"NC","name":"New caledonia"},
                {"id":159,"code":"NZ","name":"New zealand"},
                {"id":160,"code":"NI","name":"Nicaragua"},
                {"id":161,"code":"NE","name":"Niger"},
                {"id":162,"code":"NG","name":"Nigeria"},
                {"id":163,"code":"NU","name":"Niue"},
                {"id":164,"code":"NF","name":"Norfolk island"},
                {"id":165,"code":"MP","name":"Northern Mariana Islands"},
                {"id":166,"code":"NO","name":"Norway"},
                {"id":167,"code":"OM","name":"Oman"},
                {"id":168,"code":"PK","name":"Pakistan"},
                {"id":169,"code":"PW","name":"Palau"},
                {"id":170,"code":"PS","name":"Palestine"},
                {"id":171,"code":"PA","name":"Panama"},
                {"id":172,"code":"PG","name":"Papua New Guinea"},
                {"id":173,"code":"PY","name":"Paraguay"},
                {"id":174,"code":"PE","name":"Peru"},
                {"id":175,"code":"PH","name":"Philippines"},
                {"id":176,"code":"PN","name":"Pitcairn"},
                {"id":177,"code":"PL","name":"Poland"},
                {"id":178,"code":"PT","name":"Portugal"},
                {"id":179,"code":"PR","name":"Puerto rico"},
                {"id":180,"code":"QA","name":"Qatar"},
                {"id":181,"code":"RE","name":"Réunion"},
                {"id":182,"code":"RO","name":"Romania"},
                {"id":183,"code":"RU","name":"Russian Federation"},
                {"id":184,"code":"RW","name":"Rwanda"},
                {"id":185,"code":"BL","name":"Saint Barthélemy"},
                {"id":186,"code":"SH","name":"Saint Helena"},
                {"id":187,"code":"KN","name":"Saint Kitts and Nevis"},
                {"id":188,"code":"LC","name":"Saint Lucia"},
                {"id":189,"code":"MF","name":"Saint Martin (french part)"},
                {"id":190,"code":"PM","name":"Saint Pierre and Miquelon"},
                {"id":191,"code":"VC","name":"Saint Vincent and the Grenadines"},
                {"id":192,"code":"WS","name":"Samoa"},
                {"id":193,"code":"SM","name":"San Marino"},
                {"id":194,"code":"ST","name":"Sao Tome and Principe"},
                {"id":195,"code":"SA","name":"Saudi Arabia"},
                {"id":196,"code":"SN","name":"Senegal"},
                {"id":197,"code":"RS","name":"Serbia"},
                {"id":198,"code":"SC","name":"Seychelles"},
                {"id":199,"code":"SL","name":"Sierra Leone"},
                {"id":200,"code":"SG","name":"Singapore"},
                {"id":201,"code":"SX","name":"Sint Maarten (dutch part)"},
                {"id":202,"code":"SK","name":"Slovakia"},
                {"id":203,"code":"SI","name":"Slovenia"},
                {"id":204,"code":"SB","name":"Solomon Islands"},
                {"id":205,"code":"SO","name":"Somalia"},
                {"id":206,"code":"ZA","name":"South Africa"},
                {"id":207,"code":"GS","name":"South Georgia and the South Sandwich Islands"},
                {"id":208,"code":"SS","name":"South Sudan"},
                {"id":209,"code":"ES","name":"Spain"},
                {"id":210,"code":"LK","name":"Sri Lanka"},
                {"id":211,"code":"SD","name":"Sudan"},
                {"id":212,"code":"SR","name":"Suriname"},
                {"id":213,"code":"SJ","name":"Svalbard and Jan Mayen"},
                {"id":214,"code":"SZ","name":"Swaziland"},
                {"id":215,"code":"SE","name":"Sweden"},
                {"id":216,"code":"CH","name":"Switzerland"},
                {"id":217,"code":"SY","name":"Syrian Arab Republic"},
                {"id":218,"code":"TW","name":"Taiwan"},
                {"id":219,"code":"TJ","name":"Tajikistan"},
                {"id":220,"code":"TZ","name":"Tanzania"},
                {"id":221,"code":"TH","name":"Thailand"},
                {"id":222,"code":"TL","name":"Timor-leste"},
                {"id":223,"code":"TG","name":"Togo"},
                {"id":224,"code":"TK","name":"Tokelau"},
                {"id":225,"code":"TO","name":"Tonga"},
                {"id":226,"code":"TT","name":"Trinidad and Tobago"},
                {"id":227,"code":"TN","name":"Tunisia"},
                {"id":228,"code":"TR","name":"Turkey"},
                {"id":229,"code":"TM","name":"Turkmenistan"},
                {"id":230,"code":"TC","name":"Turks and Caicos Islands"},
                {"id":231,"code":"TV","name":"Tuvalu"},
                {"id":232,"code":"UG","name":"Uganda"},
                {"id":233,"code":"UA","name":"Ukraine"},
                {"id":234,"code":"AE","name":"United Arab Emirates"},
                {"id":235,"code":"GB","name":"United Kingdom"},
                {"id":236,"code":"US","name":"United States"},
                {"id":237,"code":"UM","name":"United States minor outlying islands"},
                {"id":238,"code":"UY","name":"Uruguay"},
                {"id":239,"code":"UZ","name":"Uzbekistan"},
                {"id":240,"code":"VU","name":"Vanuatu"},
                {"id":241,"code":"VE","name":"Venezuela"},
                {"id":242,"code":"VN","name":"Viet Nam"},
                {"id":243,"code":"VG","name":"Virgin Islands"},
                {"id":244,"code":"VI","name":"Virgin Islands"},
                {"id":245,"code":"WF","name":"Wallis and Futuna"},
                {"id":246,"code":"EH","name":"Western Sahara"},
                {"id":247,"code":"YE","name":"Yemen"},
                {"id":248,"code":"ZM","name":"Zambia"},
                {"id":249,"code":"ZW","name":"Zimbabwe"}]
