FORMAT: 1A

# HR Solution API

API pro produkt HR solution.

## Allowed HTTPs requests:

- `POST` - Creates or updates a resource
- `PUT` - Updates a resource
- `GET` - Retrieves a resource or list of resources
- `DELETE` - Delete a resource

## Typical Server Responses

- 200 `OK` - The request was successful (some API calls may return 201 instead).
- 201 `Created` - The request was successful and a resource was created.
- 204 `No Content` - The request was successful but there is no representation to return (that is, the response is empty).
- 400 `Bad Request` - The request could not be understood or was missing required parameters.
- 401 `Unauthorized` - Authentication failed or user does not have permissions for the requested operation.
- 403 `Forbidden` - Access denied.
- 404 `Not Found` - Resource was not found.
- 405 `Method Not Allowed` - Requested method is not supported for the specified resource.
- 429 `Too Many Requests` - Exceeded API limits. Pause requests, wait one minute, and try again.
- 503 `Service Unavailable` - The service is temporary unavailable. Try again later.

> Čas ve všech položkách (pokud není řečeno jinak) je unix_time plus ms (http://www.epochconverter.com).

# Group

Descrition.

## Resource [/url]

### Operation [POST]

Description.

#### Práce s token

+ Request (application/json)

    + Headers

            HEADER: value

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            {"response":"string"}

# Group Account

 Práce s účtem uživatele.

## Consultations [/account/consultations]

### Operation [GET]
Get list of users consultations

+ Request

    + Headers

            Access-Control-Allow-Origin: *
            X-Auth-token: {token}

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
    
            {
              "consultation_hours_available": 780,
              "completed_consultation": [
                {
                  "consultation_date": 1010231354,
                  "consultation_form": "CONSULTATION_BY_PHONE",
                  "person_id": 1,
                  "first_name": "František",
                  "last_name": "Vomáčka",
                  "consultation_length": 90
                },
                {
                  "consultation_date": 101012356454,
                  "consultation_form": "CONSULTATION_INPERSON_DAPS",
                  "person_id": 1,
                  "first_name": "František",
                  "last_name": "Vomáčka",
                  "consultation_length": 60
                },
                {
                  "consultation_date": 1013231354,
                  "consultation_form": "CONSULTATION_INPERSON",
                  "person_id": 1,
                  "first_name": "František",
                  "last_name": "Vomáčka",
                  "consultation_length": 75
                }
              ],
              "uncompleted_consultation": [
                {
                  "consultation_date": 1010231354,
                  "consultation_form": "CONSULTATION_BY_PHONE",
                  "person_id": 1,
                  "first_name": "František",
                  "last_name": "Vomáčka",
                  "consultation_length": 90
                },
                {
                  "consultation_date": 101012356454,
                  "consultation_form": "CONSULTATION_INPERSON_DAPS",
                  "person_id": 1,
                  "first_name": "František",
                  "last_name": "Vomáčka",
                  "consultation_length": 60
                },
                {
                  "consultation_date": 1013231354,
                  "consultation_form": "CONSULTATION_INPERSON",
                  "person_id": 1,
                  "first_name": "František",
                  "last_name": "Vomáčka",
                  "consultation_length": 75
                }
              ]
            }

## Registrace uživatele [/account/registration]

### Operation [POST]

Description.

#### Registrace uživatele

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {
               "first_name": "first_name",
               "last_name": "last_name",
                "email": "email",
                "phone": "333 666 999",
                "login": "login_name",
                "password": "PASSWORD",
                "verify_password": "PASSWORD"
                
            }


+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            {
                "messages": [
                    {"i18nKey":"i18n_key_success_registration","type":"success"}
                ]
            }
 

+ Response 400 (application/json)

    + Headers

            Accept: application/json

    + Body

             {
                "messages": [
                    {"i18nKey":"i18n_key_error_registration_input","type":"error"}
                ]
            }
             
## Potvrzení registrace uživatele [/account/registrationverify]

### Operation [POST]

#### Registrace uživatele

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {
               "profileStatusKey": "key"
                
            }


+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            {
                "messages": [
                    {"i18nKey":"i18n_key_succes_registration_verify","type":"success"}
                ]
            }
            
 

+ Response 400 (application/json)

    + Headers

            Accept: application/json

    + Body

            {
                "messages": [
                    {"i18nKey":"i18n_key_error_registration_verify_input","type":"error"}
                ]
            }

+ Response 401 (application/json)

    + Headers

            Accept: application/json

    + Body

            {
                "messages": [
                    {"i18nKey":"i18n_key_error_registration_verify_auth","type":"error"}
                ]
            }
            
      
## Languages Collection [/language]

### Operation [GET]

Description.

#### List all Languages

+ Request (application/json)

    + Headers

              Access-Control-Allow-Origin: *
              

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
 
 
            [{
                "id": 1,
                "description": "Angličtina",
                "i18nKey": "en"
            },{
                 
                "id": 2,
                 "description": "Čeština",
                "i18nKey": "cs"
            }] 
            
## Countries Collection [/country]

### Operation [GET]

Description.

#### List all Countries

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
             

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
            
                [{"id":1,"i18nKey":"AF","description":"Afghanistan"},
                {"id":2,"i18nKey":"AX","description":"Åland Islands"},
                {"id":3,"i18nKey":"AL","description":"Albania"},
                {"id":4,"i18nKey":"DZ","description":"Algeria"},
                {"id":5,"i18nKey":"AS","description":"American Samoa"},
                {"id":6,"i18nKey":"AD","description":"Andorra"},
                {"id":7,"i18nKey":"AO","description":"Angola"},
                {"id":8,"i18nKey":"AI","description":"Anguilla"},
                {"id":9,"i18nKey":"AQ","description":"Antarctica"},
                {"id":10,"i18nKey":"AG","description":"Antigua and Barbuda"},
                {"id":11,"i18nKey":"AR","description":"Argentina"},
                {"id":12,"i18nKey":"AM","description":"Armenia"},
                {"id":13,"i18nKey":"AW","description":"Aruba"},
                {"id":14,"i18nKey":"AU","description":"Australia"},
                {"id":15,"i18nKey":"AT","description":"Austria"},
                {"id":16,"i18nKey":"AZ","description":"Azerbaijan"},
                {"id":17,"i18nKey":"BS","description":"Bahamas"},
                {"id":18,"i18nKey":"BH","description":"Bahrain"},
                {"id":19,"i18nKey":"BD","description":"Bangladesh"},
                {"id":20,"i18nKey":"BB","description":"Barbados"},
                {"id":21,"i18nKey":"BY","description":"Belarus"},
                {"id":22,"i18nKey":"BE","description":"Belgium"},
                {"id":23,"i18nKey":"BZ","description":"Belize"},
                {"id":24,"i18nKey":"BJ","description":"Benin"},
                {"id":25,"i18nKey":"BM","description":"Bermuda"},
                {"id":26,"i18nKey":"BT","description":"Bhutan"},
                {"id":27,"i18nKey":"BO","description":"Bolivia"},
                {"id":28,"i18nKey":"BQ","description":"Bonaire"},
                {"id":29,"i18nKey":"BA","description":"Bosnia and Herzegovina"},
                {"id":30,"i18nKey":"BW","description":"Botswana"},
                {"id":31,"i18nKey":"BV","description":"Bouvet Island"},
                {"id":32,"i18nKey":"BR","description":"Brazil"},
                {"id":33,"i18nKey":"IO","description":"British indian ocean territory"},
                {"id":34,"i18nKey":"BN","description":"Brunei Darussalam"},
                {"id":35,"i18nKey":"BG","description":"Bulgaria"},
                {"id":36,"i18nKey":"BF","description":"Burkina Faso"},
                {"id":37,"i18nKey":"BI","description":"Burundi"},
                {"id":38,"i18nKey":"KH","description":"Cambodia"},
                {"id":39,"i18nKey":"CM","description":"Cameroon"},
                {"id":40,"i18nKey":"CA","description":"Canada"},
                {"id":41,"i18nKey":"CV","description":"Cape Verde"},
                {"id":42,"i18nKey":"KY","description":"Cayman Islands"},
                {"id":43,"i18nKey":"CF","description":"Central African Republic"},
                {"id":44,"i18nKey":"TD","description":"Chad"},
                {"id":45,"i18nKey":"CL","description":"Chile"},
                {"id":46,"i18nKey":"CN","description":"China"},
                {"id":47,"i18nKey":"CX","description":"Christmas Island"},
                {"id":48,"i18nKey":"CC","description":"Cocos (keeling) Islands"},
                {"id":49,"i18nKey":"CO","description":"Colombia"},
                {"id":50,"i18nKey":"KM","description":"Comoros"},
                {"id":51,"i18nKey":"CG","description":"Congo"},
                {"id":52,"i18nKey":"CD","description":"Congo"},
                {"id":53,"i18nKey":"CK","description":"Cook Islands"},
                {"id":54,"i18nKey":"CR","description":"Costa Uica"},
                {"id":55,"i18nKey":"CI","description":"Côte d'ivoire"},
                {"id":56,"i18nKey":"HR","description":"Croatia"},
                {"id":57,"i18nKey":"CU","description":"Cuba"},
                {"id":58,"i18nKey":"CW","description":"Curaçao"},
                {"id":59,"i18nKey":"CY","description":"Cyprus"},
                {"id":60,"i18nKey":"CZ","description":"Czech Republic"},
                {"id":61,"i18nKey":"DK","description":"Denmark"},
                {"id":62,"i18nKey":"DJ","description":"Djibouti"},
                {"id":63,"i18nKey":"DM","description":"Dominica"},
                {"id":64,"i18nKey":"DO","description":"Dominican Republic"},
                {"id":65,"i18nKey":"EC","description":"Ecuador"},
                {"id":66,"i18nKey":"EG","description":"Egypt"},
                {"id":67,"i18nKey":"SV","description":"El Salvador"},
                {"id":68,"i18nKey":"GQ","description":"Equatorial Guinea"},
                {"id":69,"i18nKey":"ER","description":"Eritrea"},
                {"id":70,"i18nKey":"EE","description":"Estonia"},
                {"id":71,"i18nKey":"ET","description":"Ethiopia"},
                {"id":72,"i18nKey":"FK","description":"Falkland Islands"},
                {"id":73,"i18nKey":"FO","description":"Faroe Islands"},
                {"id":74,"i18nKey":"FJ","description":"Fiji"},
                {"id":75,"i18nKey":"FI","description":"Finland"},
                {"id":76,"i18nKey":"FR","description":"France"},
                {"id":77,"i18nKey":"GF","description":"French Guiana"},
                {"id":78,"i18nKey":"PF","description":"French Polynesia"},
                {"id":79,"i18nKey":"TF","description":"French Southern Territories"},
                {"id":80,"i18nKey":"GA","description":"Gabon"},
                {"id":81,"i18nKey":"GM","description":"Gambia"},
                {"id":82,"i18nKey":"GE","description":"Georgia"},
                {"id":83,"i18nKey":"DE","description":"Germany"},
                {"id":84,"i18nKey":"GH","description":"Ghana"},
                {"id":85,"i18nKey":"GI","description":"Gibraltar"},
                {"id":86,"i18nKey":"GR","description":"Greece"},
                {"id":87,"i18nKey":"GL","description":"Greenland"},
                {"id":88,"i18nKey":"GD","description":"Grenada"},
                {"id":89,"i18nKey":"GP","description":"Guadeloupe"},
                {"id":90,"i18nKey":"GU","description":"Guam"},
                {"id":91,"i18nKey":"GT","description":"Guatemala"},
                {"id":92,"i18nKey":"GG","description":"Guernsey"},
                {"id":93,"i18nKey":"GN","description":"Guinea"},
                {"id":94,"i18nKey":"GW","description":"Guinea-bissau"},
                {"id":95,"i18nKey":"GY","description":"Guyana"},
                {"id":96,"i18nKey":"HT","description":"Haiti"},
                {"id":97,"i18nKey":"HM","description":"Heard Island and Mcdonald Islands"},
                {"id":98,"i18nKey":"VA","description":"Holy see (vatican city state)"},
                {"id":99,"i18nKey":"HN","description":"Honduras"},
                {"id":100,"i18nKey":"HK","description":"Hong Kong"},
                {"id":101,"i18nKey":"HU","description":"Hungary"},
                {"id":102,"i18nKey":"IS","description":"Iceland"},
                {"id":103,"i18nKey":"IN","description":"India"},
                {"id":104,"i18nKey":"ID","description":"Indonesia"},
                {"id":105,"i18nKey":"IR","description":"Iran"},
                {"id":106,"i18nKey":"IQ","description":"Iraq"},
                {"id":107,"i18nKey":"IE","description":"Ireland"},
                {"id":108,"i18nKey":"IM","description":"Isle of man"},
                {"id":109,"i18nKey":"IL","description":"Israel"},
                {"id":110,"i18nKey":"IT","description":"Italy"},
                {"id":111,"i18nKey":"JM","description":"Jamaica"},
                {"id":112,"i18nKey":"JP","description":"Japan"},
                {"id":113,"i18nKey":"JE","description":"Jersey"},
                {"id":114,"i18nKey":"JO","description":"Jordan"},
                {"id":115,"i18nKey":"KZ","description":"Kazakhstan"},
                {"id":116,"i18nKey":"KE","description":"Kenya"},
                {"id":117,"i18nKey":"KI","description":"Kiribati"},
                {"id":118,"i18nKey":"KP","description":"Korea"},
                {"id":119,"i18nKey":"KR","description":"Korea"},
                {"id":120,"i18nKey":"KW","description":"Kuwait"},
                {"id":121,"i18nKey":"KG","description":"Kyrgyzstan"},
                {"id":122,"i18nKey":"LA","description":"Lao People's Democratic Republic"},
                {"id":123,"i18nKey":"LV","description":"Latvia"},
                {"id":124,"i18nKey":"LB","description":"Lebanon"},
                {"id":125,"i18nKey":"LS","description":"Lesotho"},
                {"id":126,"i18nKey":"LR","description":"Liberia"},
                {"id":127,"i18nKey":"LY","description":"Libya"},
                {"id":128,"i18nKey":"LI","description":"Liechtenstein"},
                {"id":129,"i18nKey":"LT","description":"Lithuania"},
                {"id":130,"i18nKey":"LU","description":"Luxembourg"},
                {"id":131,"i18nKey":"MO","description":"Macao"},
                {"id":132,"i18nKey":"MK","description":"Macedonia"},
                {"id":133,"i18nKey":"MG","description":"Madagascar"},
                {"id":134,"i18nKey":"MW","description":"Malawi"},
                {"id":135,"i18nKey":"MY","description":"Malaysia"},
                {"id":136,"i18nKey":"MV","description":"Maldives"},
                {"id":137,"i18nKey":"ML","description":"Mali"},
                {"id":138,"i18nKey":"MT","description":"Malta"},
                {"id":139,"i18nKey":"MH","description":"Marshall Islands"},
                {"id":140,"i18nKey":"MQ","description":"Martinique"},
                {"id":141,"i18nKey":"MR","description":"Mauritania"},
                {"id":142,"i18nKey":"MU","description":"Mauritius"},
                {"id":143,"i18nKey":"YT","description":"Mayotte"},
                {"id":144,"i18nKey":"MX","description":"Mexico"},
                {"id":145,"i18nKey":"FM","description":"Micronesia"},
                {"id":146,"i18nKey":"MD","description":"Moldova"},
                {"id":147,"i18nKey":"MC","description":"Monaco"},
                {"id":148,"i18nKey":"MN","description":"Mongolia"},
                {"id":149,"i18nKey":"ME","description":"Montenegro"},
                {"id":150,"i18nKey":"MS","description":"Montserrat"},
                {"id":151,"i18nKey":"MA","description":"Morocco"},
                {"id":152,"i18nKey":"MZ","description":"Mozambique"},
                {"id":153,"i18nKey":"MM","description":"Myanmar"},
                {"id":154,"i18nKey":"NA","description":"Namibia"},
                {"id":155,"i18nKey":"NR","description":"Nauru"},
                {"id":156,"i18nKey":"NP","description":"Nepal"},
                {"id":157,"i18nKey":"NL","description":"Netherlands"},
                {"id":158,"i18nKey":"NC","description":"New caledonia"},
                {"id":159,"i18nKey":"NZ","description":"New zealand"},
                {"id":160,"i18nKey":"NI","description":"Nicaragua"},
                {"id":161,"i18nKey":"NE","description":"Niger"},
                {"id":162,"i18nKey":"NG","description":"Nigeria"},
                {"id":163,"i18nKey":"NU","description":"Niue"},
                {"id":164,"i18nKey":"NF","description":"Norfolk island"},
                {"id":165,"i18nKey":"MP","description":"Northern Mariana Islands"},
                {"id":166,"i18nKey":"NO","description":"Norway"},
                {"id":167,"i18nKey":"OM","description":"Oman"},
                {"id":168,"i18nKey":"PK","description":"Pakistan"},
                {"id":169,"i18nKey":"PW","description":"Palau"},
                {"id":170,"i18nKey":"PS","description":"Palestine"},
                {"id":171,"i18nKey":"PA","description":"Panama"},
                {"id":172,"i18nKey":"PG","description":"Papua New Guinea"},
                {"id":173,"i18nKey":"PY","description":"Paraguay"},
                {"id":174,"i18nKey":"PE","description":"Peru"},
                {"id":175,"i18nKey":"PH","description":"Philippines"},
                {"id":176,"i18nKey":"PN","description":"Pitcairn"},
                {"id":177,"i18nKey":"PL","description":"Poland"},
                {"id":178,"i18nKey":"PT","description":"Portugal"},
                {"id":179,"i18nKey":"PR","description":"Puerto rico"},
                {"id":180,"i18nKey":"QA","description":"Qatar"},
                {"id":181,"i18nKey":"RE","description":"Réunion"},
                {"id":182,"i18nKey":"RO","description":"Romania"},
                {"id":183,"i18nKey":"RU","description":"Russian Federation"},
                {"id":184,"i18nKey":"RW","description":"Rwanda"},
                {"id":185,"i18nKey":"BL","description":"Saint Barthélemy"},
                {"id":186,"i18nKey":"SH","description":"Saint Helena"},
                {"id":187,"i18nKey":"KN","description":"Saint Kitts and Nevis"},
                {"id":188,"i18nKey":"LC","description":"Saint Lucia"},
                {"id":189,"i18nKey":"MF","description":"Saint Martin (french part)"},
                {"id":190,"i18nKey":"PM","description":"Saint Pierre and Miquelon"},
                {"id":191,"i18nKey":"VC","description":"Saint Vincent and the Grenadines"},
                {"id":192,"i18nKey":"WS","description":"Samoa"},
                {"id":193,"i18nKey":"SM","description":"San Marino"},
                {"id":194,"i18nKey":"ST","description":"Sao Tome and Principe"},
                {"id":195,"i18nKey":"SA","description":"Saudi Arabia"},
                {"id":196,"i18nKey":"SN","description":"Senegal"},
                {"id":197,"i18nKey":"RS","description":"Serbia"},
                {"id":198,"i18nKey":"SC","description":"Seychelles"},
                {"id":199,"i18nKey":"SL","description":"Sierra Leone"},
                {"id":200,"i18nKey":"SG","description":"Singapore"},
                {"id":201,"i18nKey":"SX","description":"Sint Maarten (dutch part)"},
                {"id":202,"i18nKey":"SK","description":"Slovakia"},
                {"id":203,"i18nKey":"SI","description":"Slovenia"},
                {"id":204,"i18nKey":"SB","description":"Solomon Islands"},
                {"id":205,"i18nKey":"SO","description":"Somalia"},
                {"id":206,"i18nKey":"ZA","description":"South Africa"},
                {"id":207,"i18nKey":"GS","description":"South Georgia and the South Sandwich Islands"},
                {"id":208,"i18nKey":"SS","description":"South Sudan"},
                {"id":209,"i18nKey":"ES","description":"Spain"},
                {"id":210,"i18nKey":"LK","description":"Sri Lanka"},
                {"id":211,"i18nKey":"SD","description":"Sudan"},
                {"id":212,"i18nKey":"SR","description":"Suriname"},
                {"id":213,"i18nKey":"SJ","description":"Svalbard and Jan Mayen"},
                {"id":214,"i18nKey":"SZ","description":"Swaziland"},
                {"id":215,"i18nKey":"SE","description":"Sweden"},
                {"id":216,"i18nKey":"CH","description":"Switzerland"},
                {"id":217,"i18nKey":"SY","description":"Syrian Arab Republic"},
                {"id":218,"i18nKey":"TW","description":"Taiwan"},
                {"id":219,"i18nKey":"TJ","description":"Tajikistan"},
                {"id":220,"i18nKey":"TZ","description":"Tanzania"},
                {"id":221,"i18nKey":"TH","description":"Thailand"},
                {"id":222,"i18nKey":"TL","description":"Timor-leste"},
                {"id":223,"i18nKey":"TG","description":"Togo"},
                {"id":224,"i18nKey":"TK","description":"Tokelau"},
                {"id":225,"i18nKey":"TO","description":"Tonga"},
                {"id":226,"i18nKey":"TT","description":"Trinidad and Tobago"},
                {"id":227,"i18nKey":"TN","description":"Tunisia"},
                {"id":228,"i18nKey":"TR","description":"Turkey"},
                {"id":229,"i18nKey":"TM","description":"Turkmenistan"},
                {"id":230,"i18nKey":"TC","description":"Turks and Caicos Islands"},
                {"id":231,"i18nKey":"TV","description":"Tuvalu"},
                {"id":232,"i18nKey":"UG","description":"Uganda"},
                {"id":233,"i18nKey":"UA","description":"Ukraine"},
                {"id":234,"i18nKey":"AE","description":"United Arab Emirates"},
                {"id":235,"i18nKey":"GB","description":"United Kingdom"},
                {"id":236,"i18nKey":"US","description":"United States"},
                {"id":237,"i18nKey":"UM","description":"United States minor outlying islands"},
                {"id":238,"i18nKey":"UY","description":"Uruguay"},
                {"id":239,"i18nKey":"UZ","description":"Uzbekistan"},
                {"id":240,"i18nKey":"VU","description":"Vanuatu"},
                {"id":241,"i18nKey":"VE","description":"Venezuela"},
                {"id":242,"i18nKey":"VN","description":"Viet Nam"},
                {"id":243,"i18nKey":"VG","description":"Virgin Islands"},
                {"id":244,"i18nKey":"VI","description":"Virgin Islands"},
                {"id":245,"i18nKey":"WF","description":"Wallis and Futuna"},
                {"id":246,"i18nKey":"EH","description":"Western Sahara"},
                {"id":247,"i18nKey":"YE","description":"Yemen"},
                {"id":248,"i18nKey":"ZM","description":"Zambia"},
                {"id":249,"i18nKey":"ZW","description":"Zimbabwe"}]
            
## User detail [/account]

### Operation [GET]

Description.

#### User detail

+ Request (application/json)
    + Headers

             Access-Control-Allow-Origin: *


+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
            
            {
                "first_name": "John",
                "last_name": "Doe",
                "email": "johndoe@email.cz",
                "phone": "+420 111 333 555",
                "company": "Example Company",
                "street": "Sadová",
                "city": "Ostrava",
                "zip": "702 00",
                "country": 147,
                "vat_id": "112233"
            }

### Operation [PUT]

Description.

#### User detail

+ Request (application/json)
    + Headers

             Access-Control-Allow-Origin: *
             
    + Body
    
            {
                "first_name": "John",
                "last_name": "Doe",
                "email": "email",
                "phone": "phone",
                "company": "company",
                "street": "street",
                "city": "city",
                "zip": "zip",
                "country": "country",
                "vat_id": "vat_id"
                
            }


+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
    
            {
                "messages": [
                    {"i18nKey":"i18n_key_success_user_account_update","type":"success"}
                ]
            }

+ Response 400 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
    
            {
                "messages": [
                    {"i18nKey":"i18n_key_error_user_update","type":"error"}
                ]
            }
            
## Recovery password [/account/recoverpassword]
### I need new password [POST]

Obdrzi jeden email na nemz bylo zapomenuto heslo.
Vyhleda uzivatele podle tohoto emailu, vytvori identifikacni kod a odesle email s odkazem na zmenu hesla ktery obsahuje identifikacni kod.
Pokud zadany email neexistuje nic neprovadi.
Vzdy vraci 204, aby nebylo mozne zjistovat existenci emailu v systemu.

url v emailu pro zmenu hesla je [ /passwordrecovery/newpassword?email=XXX&code=XXX ]
kde email je email pro doplneni do login page, na kterou se presmeruje po uspesne zmene hesla
a code je dlouhy retezec pro identifikaci uzivatele

+ Request

        {
            "email": "email@example.com"
        }

+ Response 204

+ Response 400 (Bad Request)

    + Header
    
            Access-Control-Allow-Origin: *
            
    + Body
    
            {
                "messages": [
                    {"i18nKey":"account_password_recovery_error","type":"error"}
                ]
            }    


## Users 401 messages [/test/messages]
### Users 401 messages [GET]
            
+ Response 401 (Unauthorized)

    + Header
    
            Access-Control-Allow-Origin: *
            
    + Body
    
            {
                "messages": [
                    {"i18nKey":"i18nKeyErrorMessageUnauthorized1","type":"error"},
                    {"i18nKey":"i18nKeyErrorMessageUnauthorized2","type":"error"},
                    {"i18nKey":"i18nKeyErrorMessageUnauthorized3","type":"error"}
                ]
            }                        
            
## Users Login [/account/login]
### Login User [POST]

+ Request (application/json)
    + Headers

             Access-Control-Allow-Origin: *
             
    + Body
    
            {
               "login": "user@yourdomain.com",
               "password": "good_password",
                 
            }
+ Response 200 (application/json)

    + Header
            
            Access-Control-Allow-Origin: *
            
    + Body
            
            {
                "user_id": 12312334,
                "token": "security_token",
                "role":["admin","user","consultant","businessman"],
                "license":["hr2","hr3","hr4","hr5","HR3L20","HR3M20"],
                "first_name":"John",
                "last_name":"Black"
            }
            
## Users Logout [/account/logout]
### Logout User [POST]

+ Request (application/json)
    + Headers

             Access-Control-Allow-Origin: *
             X-Auth-Token:aaa-asd-sfsd-123
    
+ Response 200 (application/json)
+ Response 401 (application/json)

## Users 201 message [/test/messages201]
### Users 201 message [GET]
            
+ Response 201 

    + Header
    
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4
            
    + Body
    
            {
                "messages": 
                    {"i18nKey":"i18nKeyCreatedMessage","type":"success"}
            } 
            
## Orders Collection [/account/orders]
### Operation [GET]
Description.

#### List all user orders

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            [{
            "id": 1,
            "insert_time": "1.11.2014",
            "price": "100",
            "currency": "CZK",
            "items":{
                "type": "HR4",
                "license_type": "ONE_TIME",
                "licence_status": "WAITING_FOR_PAYMENT",
                "valid_from": "",
                "valid_to": ""}
            }]

+ Response 400 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
    
            {
                "messages": [
                    {"i18nKey":"i18n_key_error_get_license_list_input","type":"error"}
                ]
            }
+ Response 401 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
    
            {
                "messages": [
                    {"i18nKey":"i18n_key_error_get_license_list_auth","type":"error"}
                ]
            }

## Order Collection [/account/{user_id}/orders]
### Operation [POST]
Create a new license orders

#### Save new license order

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    + Body

            {
                "invoice_items":{
                    "company":"company",
                    "person":"person",
                    "street":"street",
                    "city":"city",
                    "zip":"zip",
                    "country":222,
                    "ic":"ic",
                    "dic":"dic"
                },
                "modules":[{
                    "module_id":"HR4",
                    "license_id":"ONE_TIME",
                    "training":[1,2],
                    "consult_hours":5
                    },
                    {
                    "module_id":"HR4",
                    "license_id":"HALF_YEAR",
                    "training":[3,4],
                    "consult_hours":0
                    }]
            }

+ Response 201 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            {
                "messages": [
                {"i18nKey":"i18n_key_success_message_new_order_created","type":"success"}
                ]
            }    
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18n_key_error_message_new_order_not_created","type":"error"}
                 ]
            }   
            
## User's password change [/account/passwordchange]
### Operation [POST]
Description.

#### Store a changed user password

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

             Access-Control-Allow-Origin: *

    + Body
             
            {
                "messages": [
                    {"i18nKey":"i18n_key_success_message_password_change","type":"success"}
                ]
            }
             
+ Response 400 (application/json)

    + Headers

            Accept: application/json

    + Body

             {
                 "messages": [
                    {"i18nKey":"i18n_key_error_message_password_change","type":"error"}
                 ]
            }
            

## Download pdf [/order/{id}/invoice]
### Download [GET]

+ Response 200

    + Header

            Content-Type: application/pdf
            Content-Disposition: attachment; filename="invoice.pdf"
            Access-Control-Allow-Origin: *

    + Body

            Order invoice

## Person detail  [/account/hr4/person/{person_id}]

### Operation [GET]

Description.

#### Show Person detail  

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
             

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
             X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body
            
            {
            "firstName": "Person name",
            "lastName": "Person surname" ,
            "email":"person@seznam.cz",
            "position":"Boss"
            }
            
            
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages":  
                    {"i18nKey":"i18nKeyErrorMessagePersonDetail","type":"error"}
                  
            }
          
            
### Operation [PUT]

Description.

#### Save Person detail

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
             
    + Body
            
            {
            "firstName": "Person name",
            "lastName": "Person surname" ,
            "email":"person@seznam.cz",
            "position":"Boss"
            }

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body
             
            {
                 "messages":  
                    {"i18nKey":"i18nKeySuccessMessagePersonDetailUpdate","type":"success"}
                  
            }    
            
            
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages":  
                    {"i18nKey":"i18nKeyErrorMessagePersonDetailUpdate","type":"error"}
                  
            }           
            
### Operation [DELETE]

Description.

#### Delete Person

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
             
     

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            Accept: application/json
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body
            
            {
                 "messages": 
                    {"i18nKey":"i18nKeySuccessMessagePersonDetailDeleted","type":"success"}
                  
            }    
            
            
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": 
                    {"i18nKey":"i18nKeyErrorMessagePersonDetailDeleted","type":"error"}
                  
            }           
            
            
            
## Recovery password [/account/recoverynewpassword]
### new password [POST]

request to set user's password
profile_status_key - long string to recognize user
password - new password for user

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {
                "profile_status_key": "KEY",
                "password": "PASSWORD"
            }
            
+ Response 200

    + Body
    
            {
                "messages": {
                                "i18nKey": "passwordRecoveryNewPasswordSuccess",
                                "type": "success"
                            }
            }

+ Response 400

## Users 402 Payment Required [/test/messages402]
### Users 402 Payment Required [GET]
            
+ Response 402

    + Header
    
            Access-Control-Allow-Origin: *
            
    + Body
    
            {
                "data": "data"
            }
            
## HR4 person list [/account/hr4/persons]
### Operation [GET]
Get the list of persons for hr4 model and specific user.

#### List all persons

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body

            [{
            "id": 1,
            "name": "František",
            "surname": "Vomáčka",
            "position": "Kuchař",
            "diagnostic_time":"1412154655000"
            },{
            "id": 2,
            "name": "Elizabeth II.",
            "surname": "Windsor",
            "position": "Queen of the Empire",
            "diagnostic_time":null
            },{
            "id": 3,
            "name": "Silvestr",
            "surname": "Alone",
            "position": "Boxer",
            "diagnostic_time":"1406884255000"
            },{
            "id": 4,
            "name": "Arnold",
            "surname": "Schwarz",
            "position": "Krotitel predátorů",
            "diagnostic_time":null
            },{
            "id": 5,
            "name": "Elton",
            "surname": "John",
            "position": "Profesionální účastník karaoke",
            "diagnostic_time":"1409562655000"
            }]
            
+ Response 400 (application/json)

    + Headers

            Access-Control-Allow-Origin: *

    + Body
    
            {
                "messages": [
                    {"i18nKey":"i18n_key_error_get_hr_persons","type":"error"}
                ]
            }

# Group  HR4 Person Records

## HR4 person records List person's records [/account/hr4/person/{id_person}/records]

### Operation [GET]
Get the list of person's results for hr4 model and specific user.

#### List person's results

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            [{
            "result_id": 1,
            "result_date": "6.2.2014",
            "result_diagnosticurl": "http://scanner.forHrsolution.cz?code=255662",
            "status": "DIAGNOSTIC_COMPLETED"
            },{
            "result_id": 2,
            "result_date": "6.3.2014",
            "result_diagnosticurl": "http://scanner.forHrsolution.cz?code=255662",
            "status": "WAITING_FOR_DIAGNOSTIC"
            },{
            "result_id": 3,
            "result_date": "24.7.2014",
            "result_diagnosticurl": "http://scanner.forHrsolution.cz?code=255662",
            "status": "DIAGNOSTIC_COMPLETED"
            },{
            "result_id": 4,
            "result_date": "16.11.2014",
            "result_diagnosticurl": "http://scanner.forHrsolution.cz?code=255662",
            "status": "DIAGNOSTIC_COMPLETED"
            }]
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessagePersonDetailResults","type":"error"}
                 ]
            } 

## HR4 person records Share person's result [/account/hr4/person/{person_id}/share/{id_record}]

### Operation [POST]
Share person's result

#### Share person's result

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    + Body

             {
                "EmailsToShare": "person@seznam.cz,person@seznam.cz,person@seznam.cz"
                 
            }

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                "messages": [
                {"i18nKey":"i18nKeySuccessMessagePersonDetailShare","type":"success"}
                ]
            }    
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessagePersonDetailShare","type":"error"}
                 ]
            }    
 
## HR4 person records DiagnosticUrl email [/account/hr4/person/{person_id}/sendscannerurl]
            
### Operation [POST]
Send email for diagnostic to the person

#### Send email whith scaner url

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    + Body

             {
                "person_email": "person@seznam.cz"
                 
            }

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                "messages": [
                {"i18nKey":"i18nKeySuccessMessagePersonDetailDiagnosticEmail","type":"success"}
                 ] 
            }    
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessagePersonDetailDiagnosticEmail","type":"error"}
                  ] 
            }           

## HR4 person records delete record [/account/hr4/person/{person_id}/delete/{id_record}]
             
### Operation [DELETE]
Delete result of person

#### Delete result of person

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                "messages":[  
                {"i18nKey":"i18nKeySuccessMessagePersonDetailDeleteResult","type":"success"}
                 ]
            }    
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages":[  
                    {"i18nKey":"i18nKeyErrorMessagePersonDetailDeleteResult","type":"error"}
                  ]
            }           
                  
# Group Consultation              
                  
## HR4 New Consultation [/account/hr4/newconsultation]

### Operation [GET]
Get New Consultation details for hr4 model.

#### New Consultation details

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
            "consultationForms": [ 
             {"title":"Telefon","code":"PHONE"},
             {"title":"Osobně v DAP Services","code":"INPERSONDAPS"},
             {"title":"Osobně u nás","code":"INPERSON"}
 
             ],
             "consultationLenght":"30 min",
             "description":"hr4_new_consultation_diagnostic_description_Text"
             }
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageNewConsultation","type":"error"}
                 ]
            }           
            
### Operation [POST]
Order New Consultation

#### Order New Consultation

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    + Body

             {
                "person_id": "23",
                "result_id": "23455",
                "user_id": "12",
                "consultation_date": "12.11.20014 13:30",
                "consultation_form": "INPERSONDAPS",
                "consultation_Lenght": "30 min"
                 
            }

+ Response 201 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                "messages": [
                {"i18nKey":"i18nKeySuccessMessageNewConsultationCreated","type":"success"}
                ]
            }    
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageNewConsultationNotCreated","type":"error"}
                 ]
            }   
 
# Group  modules 
            
## Get module license configuration [/account/{id}/order/module/{id_module}]

### Operation [GET]
Get the list of possible licences for module

#### List person's results

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-Auth-token: token
            

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    + Body

            [
                {
                  "type": "HALF_YEAR",
                  "resource_name":"order_module_license_type_half_year_license",
                  "price": 100,
                  "consultation_hours": 3,
                  "consultation_hour_price": 5,
                  "valid_until":1449229755000,
                  "training": [
                    {
                      "id": 1,
                      "training_name":"module_training_1",
                      "price": 15,
                      "required": false
                    },
                    {
                      "id": 2,
                      "training_name":"module_training_2",
                      "price": 25,
                      "required": false
                    },
                    {
                      "id": 3,
                      "training_name":"module_training_3",
                      "price": 12,
                      "required": false
                    },
                    {
                      "id": 4,
                      "training_name":"module_training_4",
                      "price": 10,
                      "required": false
                    },
                    {
                      "id": 5,
                      "training_name":"module_training_5",
                      "price": 5,
                      "required": true
                    }
                  ]
                },
                {
                  "type": "ONE_TIME",
                  "resource_name":"order_module_license_type_single_license",
                  "price": 4,
                  "consultation_hours": 1,
                  "consultation_hour_price": 10,
                  "training": [
                    {
                      "id": 1,
                      "training_name":"module_training_1",
                      "price": 17,
                      "required": false
                    },
                    {
                      "id": 2,
                      "training_name":"module_training_2",
                      "price": 30,
                      "required": false
                    },
                    {
                      "id": 5,
                      "training_name":"module_training_5",
                      "price": 10,
                      "required": true
                    }
                  ]
                }
              ]

+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18n_key_error_message_module_license","type":"error"}
                 ]
            }     

# Group Person

Page for create new persons and diagnostic (/hr4/newPersons)
 
## create new persons with new diagnostics [/account/{id}/hr4/persons/create]

### Operation [POST]

Create new persons, create new diagnostics for each person and check if diagnostics urls is unique. Sends email to selected persons.
If checking diagnostic url fail it return some 40X to show error message or page with message to contact admin.

#### complete creating new persons

+ Request (application/json)

    + Headers
    
            Access-Control-Allow-Origin: *

    + Body

            {
                "words": ["Me", "Work", "Missile", "Grandmother"],
               "langCode":"en",
                "persons": [
                    {
                        "sendMail": true,
                        "firstName": "Karl",
                        "lastName": "Schlanshamer",
                        "email": "karlAusDeutchland@germany.de",
                        "position": "Boss"
                    },{
                        "sendMail": false,
                        "firstName": "Sergei",
                        "lastName": "Dimitrienko",
                        "email": "dinitriSergei@motherrussia.ru",
                        "position": "IT Expert"
                    }
                ]
            }

+ Response 200  (application/json)

    + Headers
    
            Access-Control-Allow-Origin: *
    
    + Body
    
            {
                 "messages": [
                    {"i18nKey":"hr4_new_person_submit_successful","type":"success"}
                 ]
            }
    
+ Response 400  (application/json)
    
    + Headers
    
            Access-Control-Allow-Origin: *



## Diagnostic [/{id}/hr4/diagnostic/{idr}/words]

### Operation [GET]
Get the list of words from diagnostic.

#### List of words by recordId

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                "words":  ["Testování", "Krev", "Já", "Nátlak"],
                "langCode":"cs"
             }
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessagePersonDetail","type":"error"}
                 ]
            }

## Diagnostic language [/hr4/diagnostic/supporteddiagnosticlangs]

### Operation [GET]
Get the list of supported languages for diagnostic.

#### List of supported languages

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body
    
            {
                "supportedDiagnosticLanguages":["en", "cs"],
                "maxDiagnosticWords":10,
                "baseDiagnosticWords": 
                {"cs":[
                    {"order": null, "id": 21266, "value": "Já"},
                    {"order": null, "id": 21271, "value": "Moje psychika"},
                    {"order": null, "id": 21357, "value": "Informace"}
                ] ,
                 "en":[
                    {"order": null, "id": 22366, "value": "Me"},
                    {"order": null, "id": 22271, "value": "My psyche"},
                    {"order": null, "id": 22357, "value": "Information"}
                ]}
                
                 
            }
            
+ Response 400 (application/json)

    + Headers

            Accept: application/json
            Access-Control-Allow-Origin: *
            X-License-Hr4: true
            Access-Control-Expose-Headers: X-License-Hr4

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageDiagnosticLanguages","type":"error"}
                 ]
            }



# Group result            
## Vystup pro HR4 format 1 and 2 [/result/{idresult}/generate]
### Result 1 and 2 [POST]

+ Request 

            {
                "scan_data_ids":[4343]
            }
            
+ Response 200

            {
                "person":{"name":"John","surname":"Dove","diagnostic_time":1234567890123,"position":"manager"},
                "1":{"description":["model1_i18nkey","model2_i18nkey"]},
                "2":{"description":["assigment1_i18nkey","assigment2_i18nkey"]},
                "230":{"value":90,"description":["trait1_text1_i18nkey","trait1_text2_i18nkey"],"color":"GREEN","warning":true},
                "112":{"value":15,"description":["trait2_text3_i18nkey"],"color":"RED","warning":false},
                "149":{"value":55,"description":["trait3_text3_i18nkey"],"color":"GREEN","warning":false},
                "240":{"value":65,"description":["trait4_text3_i18nkey"],"color":"GREEN","warning":false},
                "121":{"value":45,"description":["trait5_text3_i18nkey"],"color":"GREEN"},
                "229":{"value":35,"description":["trait6_text3_i18nkey"],"color":"YELLOW"},
                "104":{"value":20,"description":["trait7_text3_i18nkey"],"color":"YELLOW"},
                "226":{"value":5,"description":["trait8_text3_i18nkey"],"color":"RED"},
                "132":{"value":100,"description":["trait9_text3_i18nkey","trait9_text4_i18nkey"],"color":"GREEN","warning":true},
                "130":{"value":0,"description":["trait10_text3_i18nkey"],"color":"RED"},
                "170":{"value":68,"description":["trait11_text3_i18nkey"],"color":"GREEN"},
                "136":{"value":55,"description":["trait12_text3_i18nkey"],"color":"GREEN"},
                "119":{"value":35,"description":["trait13_text3_i18nkey"],"color":"YELLOW"},
                "239":{"value":40,"description":["trait14_text3_i18nkey"],"color":"YELLOW"},
                "143":{"value":73,"description":["trait15_text3_i18nkey"],"color":"GREEN"},
                "148":{"value":67,"description":["trait16_text3_i18nkey"],"color":"GREEN"},
                "234":{"value":73,"description":["trait17_text3_i18nkey"],"color":"GREEN"},
                "164":{"value":84,"description":["trait18_text3_i18nkey","trait18_text1_i18nkey"],"color":"GREEN","warning":true},
                "160":{"value":73,"description":["trait19_text3_i18nkey"],"color":"GREEN"},
                "127":{"value":100,"description":["trait20_text3_i18nkey","trait20_text1_i18nkey"],"color":"GREEN","warning":true},
                "235":[{"name":"role1_name_i18nkey","description":["role1_text1_i18nkey"]},
                    {"name":"role2_name_i18nkey","description":["role2_text1_i18nkey"]},
                    {"name":"role3_name_i18nkey","description":["role3_text1_i18nkey"]}],
                "237":{"description":["assigment2_i18nkey"]},
                "236":{"description":["model1_i18nkey"]},
                "204":{"ideals":["Pracovní prostředí","Uznani kolegu","Stravenky","Anglictina"],
                        "satisfactors_motivators":["Týmová spolupráce","Plat","Dovolena navic","Uznani kolegu","Stravenky","Anglictina"],
                        "operators":["Jsem agresivní","Jsem trestán/a","Konkurence","Lidé","Moje obrana","Moje vůle","Myslím","Můj strach","Nechci","Nesmím","Neumím","Námaha","Organizuji","Peníze","Pomalost","Povinnosti","Počítače","Prožívání","Rozhoduji","Rychlost","Samostatný/á/","Skutečnost","Spolupráce","Vidím","Úspěch","Čas"],
                        "stressors":["Stres","Plat","Dovolena navic","Uznani kolegu","Stravenky","Anglictina"],
                        "destructors":["Fialová barva","Plat","Uznani kolegu","Stravenky","Anglictina"]
                },
                "241": [{"id": 0, "name": "role1_name_i18nkey", "value": 100},
                    {"id": 1, "name": "role2_name_i18nkey", "value": 95},
                    {"id": 2, "name": "role3_name_i18nkey", "value": 90},
                    {"id": 3, "name": "role4_name_i18nkey", "value": 80},
                    {"id": 4, "name": "role5_name_i18nkey", "value": 75},
                    {"id": 5, "name": "role6_name_i18nkey", "value": 70},
                    {"id": 6, "name": "role7_name_i18nkey", "value": 65},
                    {"id": 7, "name": "role8_name_i18nkey", "value": 60},
                    {"id": 8, "name": "role9_name_i18nkey", "value": 55},
                    {"id": 9, "name": "role10_name_i18nkey", "value": 50},
                    {"id": 10, "name": "role11_name_i18nkey", "value": 50},
                    {"id": 11, "name": "role12_name_i18nkey", "value": 45},
                    {"id": 12, "name": "role13_name_i18nkey", "value": 45},
                    {"id": 13, "name": "role14_name_i18nkey", "value": 40},
                    {"id": 14, "name": "role15_name_i18nkey", "value": 35},
                    {"id": 15, "name": "role16_name_i18nkey", "value": 30},
                    {"id": 16, "name": "role17_name_i18nkey", "value": 30},
                    {"id": 17, "name": "role18_name_i18nkey", "value": 25},
                    {"id": 18, "name": "role19_name_i18nkey", "value": 20},
                    {"id": 19, "name": "role20_name_i18nkey", "value": 20}]
            }
            
+ Response 400 

    + Header

            Access-Control-Allow-Origin: *

    + Body

            {
                "messages": 
                    {"i18nKey":"result_error_code","type":"error"}
            }
            
## List of user training [/account/training]

### Operation [GET]
Get the list of all user training.

#### List of user training

+ Request (application/json)

    + Headers

            Access-Control-Allow-Origin: *

+ Response 200 (application/json)

    + Headers

            Access-Control-Allow-Origin: *
            
    + Body
    
            [
                {
                    "id": 1,
                    "training_name": "Training name 1",
                    "order_date": 112233,
                    "training_date": 223344,
                    "price": 1000,
                    "currency": "CZK",
                    "status": "SCHEDULED"
                },
                {
                    "id": 2,
                    "training_name": "Training name 2",
                    "order_date": 112233,
                    "training_date": 333344,
                    "price": 1500,
                    "currency": "CZK",
                    "status": "FINISHED"
                },
                {
                    "id": 3,
                    "training_name": "Training name 3",
                    "order_date": 11223344,
                    "price": 1500,
                    "currency": "CZK",
                    "status": "NOT_SCHEDULED"
                }
            ]


# Group  HR3 

## HR3 groups dashboard list [/hr3/groups]

### Groups list for authenticated user. [GET]

+ Request

    + Headers
    
            X-Auth-token: your_token
            Accept: application/json

+ Response 200 (application/json)

    + Body

            [
                {
                "id": "12",
                "name": "Company Name 1",
                "created_date": "1412154655000",
                "diagnostics_completed": "6",
                "members_count": "8"
                },
                {
                "id": "13",
                "name": "Company Name 2 is really really long",
                "created_date": "1428638400000",
                "diagnostics_completed": "4",
                "members_count": "12"
              },
              {
                "id": "14",
                "name": "Company Name 3",
                "created_date": "1406884255000",
                "diagnostics_completed": "5",
                "members_count": "5"
              }
              ,
              {
                "id": "15",
                "name": "Company Name 4",
                "created_date": "1406884255000",
                "diagnostics_completed": "4",
                "members_count": "0"
              }
              ,
              {
                "id": "16",
                "name": "Company Name 5",
                "created_date": "1010123564",
                "diagnostics_completed": "2",
                "members_count": "12"
              }
              ,
              {
                "id": "17",
                "name": "Company Name 6",
                "created_date": "1013231354",
                "diagnostics_completed": "5",
                "members_count": "15"
              }
            ]
            
+ Response 400 (application/json)

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessage","type":"error"}
                 ]
            } 

 
## HR3 Group detail [/hr3/groups/{group_id}]

### Show detail of group [GET]

+ Request

    + Headers

            X-Auth-token: your_token
            Accept: application/json

+ Response 200 (application/json)

    + Headers
    
            X-License-Hr3: true
            Access-Control-Expose-Headers: X-License-Hr3

    + Body

            {
                "id": "14",
                "name": "Company Name 3",
                "created_date": "1412154655000",
                "diagnostics_completed": "4",
                "members_count": "12"
            } 
            
+ Response 400 (application/json)

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageGroupDetail","type":"error"}
                 ]
            } 
 

### Create new group of persons [POST]

> TODO: we need words and language for new persons

+ Request (application/json)

    + Headers
    
            X-Auth-token: your_token
            Accept: application/json

    + Body

            {
                "name": "New group name",
                "persons":[
                    {
                    "name": "František",
                    "surname": "Vomáčka",
                    "position": "Kuchař",
                    },{
                    "name": "Elizabeth II.",
                    "surname": "Windsor",
                    "position": "Queen of the Empire",
                    },{
                    "name": "Silvestr",
                    "surname": "Alone",
                    "position": "Boxer",
                    },{
                    "name": "Arnold",
                    "surname": "Schwarz",
                    "position": "Krotitel predátorů",
                    },{
                    "name": "Elton",
                    "surname": "John",
                    "position": "Profesionální účastník karaoke",
                    }
                ]
                
            } 

+ Response 200 (application/json)

    + Body
    
            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageNewGroup","type":"success"}
                 ]
            }
    
+  Response 400 (application/json)

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageNewGroup","type":"error"}
                 ]
            } 
 

## HR3 Groups persons [/hr3/groups/{group_id}/persons]

### List group persons [GET]

+ Request

    + Headers

            X-Auth-token: your_token
            Accept: application/json

+ Response 200 (application/json)

    + Body
 
             [
              {
                "id": 1,
                "name": "František",
                "surname": "Vomáčka",
                "position": "Kuchař",
                "diagnostic_time": "1412154655000",
                "affected": false
              },
              {
                "id": 2,
                "name": "Elizabeth II.",
                "surname": "Windsor",
                "position": "Queen of the Empire",
                "diagnostic_time": null
              },
              {
                "id": 3,
                "name": "Silvestr",
                "surname": "Alone",
                "position": "Boxer",
                "diagnostic_time": "1406884255000",
                "affected": true
              },
              {
                "id": 4,
                "name": "Arnold",
                "surname": "Schwarz",
                "position": "Krotitel predátorů",
                "diagnostic_time": null
              },
              {
                "id": 5,
                "name": "Elton",
                "surname": "John",
                "position": "Profesionální účastník karaoke",
                "diagnostic_time": "1409562655000",
                "affected": false
              }
            ]
            
+ Response 400 (application/json)

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageGroupDetailPersons","type":"error"}
                 ]
            } 


### Add new persons to group [POST]

+ Request (application/json)

    + Headers
    
            X-Auth-token: your_token
            Accept: application/json

    + Body
 
            [
              {
                "id": 34,
                "name": "Sergei",
                "surname": "Dimitrienko",
                "position": "IT Expert"
              },
              {
                "id": 32,
                "name": "Karl",
                "surname": "Schwarz",
                "position": "IT Expert"
              }
            ]

+ Response 200 (application/json)
    
    + Body
    
            {
                 "messages": [
                    {"i18nKey":"i18nKeySuccessMessageGroupsPersons","type":"success"}
                 ]
            }
    
+  Response 400 (application/json)

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageGroupsPersons","type":"error"}
                 ]
            } 

 
## HR3 Group persons delete person [/hr3/groups/{group_id}/persons/{id}]
             
### Delete person from group's persons [DELETE]

+ Request (application/json)

    + Headers

            X-Auth-token: your_token
            Accept: application/json
            
+ Response 200 (application/json)

    + Body

            {
                "messages":[  
                {"i18nKey":"i18nKeySuccessMessageGroupsPersonsDeletePerson","type":"success"}
                 ]
            }    
            
+ Response 400 (application/json)

    + Body

            {
                 "messages":[  
                    {"i18nKey":"i18nKeyErrorMessageGroupsPersonsDeletePerson","type":"error"}
                  ]
            }

## HR3 Group persons send invitation [/hr3/groups/{group_id}/persons/{id}/invitation]
            
### Send email invitation for diagnostic whith scaner url [POST]

+ Request (application/json)

    + Headers

            X-Auth-token: your_token
            Accept: application/json
            
+ Response 200 (application/json)

    + Body

            {
                "messages": [
                {"i18nKey":"i18nKeySuccessMessageGroupsPersonsDiagnosticEmail","type":"success"}
                 ] 
            }    
            
+ Response 400 (application/json)

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageGroupsPersonsDiagnosticEmail","type":"error"}
                  ] 
            }           


## HR3 Groups teams [/hr3/groups/{group_id}/teams]

### Get the list of saved teams. [GET]

+ Request (application/json)

    + Headers

            X-Auth-token: your_token
            Accept: application/json

+ Response 200 (application/json)

    + Body
 
            [
              {
                "id": 43,
                "name": "Tým IT",
                "created_date": "1412154655000",
                "persons": [
                  "František Vomáčka",
                  "Silvestr Alone",
                  "Arnold Schwarz",
                  "Elton John"
                ]
              },
              {
                "id": 22,
                "name": "Administrace",
                "created_date": "1409562655000",
                "persons": [
                  "Elizabeth Windsor",
                  "Arnold Schwarz",
                  "Elton John"
                ]
              }
            ]
            
+ Response 400 (application/json)

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageGroupsTeamDetail","type":"error"}
                 ]
            } 

 
### Create new team [POST]

For this request we apply hr3 licence.

+ Request (application/json)

    + Headers
    
            X-Auth-token: your_token
            Accept: application/json
             Access-Control-Allow-Origin: *

    + Body
 
            {
            "words": 
            [
              [
                {
                  "lang_code": "cs",
                  "object_type": "WORD",
                  "label": "Já"
                },
                {
                  "lang_code": "en",
                  "object_type": "WORD",
                  "label": "Me"
                }
              ],
              [
                {
                  "lang_code": "cs",
                  "object_type": "WORD",
                  "label": "Peníze"
                },
                {
                  "lang_code": "en",
                  "object_type": "WORD",
                  "label": "Money"
                }
              ]
            ],
            "persons": [
                {
                    "sendMail": true,
                    "firstName": "Karl",
                    "lastName": "Schlanshamer",
                    "email": "karlAusDeutchland@germany.de",
                    "position": "Boss",
                    "diagnostisLanguage": "en"
                },{
                    "sendMail": false,
                    "firstName": "Sergei",
                    "lastName": "Dimitrienko",
                    "email": "dinitriSergei@motherrussia.ru",
                    "position": "IT Expert",
                    "diagnostisLanguage": "cs"
                }
            ] 
              
              
              
            }

+ Response 200  (application/json)

    + Headers
    
            X-License-Hr3: true
            Access-Control-Expose-Headers: X-License-Hr3
    
    + Body
    
            {
                 "messages": [
                    {"i18nKey":"i18nKeySuccessMessageGroupsTeamCreated","type":"success"}
                 ]
            }
    
+  Response 400 (application/json)

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageGroupsTeamCreated","type":"error"}
                 ]
            } 

 
## HR3 Groups teams delete team [/hr3/groups/{group_id}/teams/{team_id}]
             
### Delete team from group's teams [DELETE]

+ Request (application/json)

    + Headers

            X-Auth-token: your_token
            Accept: application/json

+ Response 200 (application/json)

    + Body

            {
                "messages":[  
                {"i18nKey":"i18nKeySuccessMessageGroupsTeamsDeleteTeam","type":"success"}
                 ]
            }    
            
+ Response 400 (application/json)

    + Body

            {
                 "messages":[  
                    {"i18nKey":"i18nKeyErrorMessageGroupsTeamsDeleteTeam","type":"error"}
                  ]
            }           

### Get team detail [GET]

List of words for diagnostic

+ Request (application/json)

    + Headers
 
            X-Auth-token: your_token
            Accept: application/json
 
  

+ Response 200  (application/json)

    + Headers
 
            X-License-Hr3: true
            Access-Control-Expose-Headers: X-License-Hr3
    
    + Body
    
             {
            "words": 
            [
              [
                {
                  "lang_code": "cs",
                  "object_type": "WORD",
                  "label": "Moje práce"
                },
                {
                  "lang_code": "en",
                  "object_type": "WORD",
                  "label": "My job"
                }
              ],
              [
                {
                  "lang_code": "cs",
                  "object_type": "WORD",
                  "label": "Peníze"
                },
                {
                  "lang_code": "en",
                  "object_type": "WORD",
                  "label": "Money"
                }
              ]
            ],
            "persons": [
                {
                    "sendMail": true,
                    "firstName": "Karl",
                    "lastName": "Schlanshamer",
                    "email": "karlAusDeutchland@germany.de",
                    "position": "Boss",
                    "diagnostisLanguage": "en"
                },{
                    "sendMail": false,
                    "firstName": "Sergei",
                    "lastName": "Dimitrienko",
                    "email": "dinitriSergei@motherrussia.ru",
                    "position": "IT Expert",
                    "diagnostisLanguage": "cs"
                }
            ] 
              
              
              
            }
    
+  Response 400 (application/json)

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageGroupsTeamdetail","type":"error"}
                 ]
            } 
 
 

## HR3 Groups teams share team's result [/hr3/groups/{group_id}/teams/{team_id}/sharing]

### Share team's result [POST]

+ Request (application/json)

    + Headers

            X-Auth-token: your_token
            Accept: application/json
            
    + Body

             {
                "emails_to_share": "person@seznam.cz,person@seznam.cz,person@seznam.cz"
                 
            }

+ Response 200 (application/json)

    + Body

            {
                "messages": [
                {"i18nKey":"i18nKeySuccessMessageGroupDetailShare","type":"success"}
                ]
            }    
            
+ Response 400 (application/json)

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageGroupDetailShare","type":"error"}
                 ]
            } 
 
 
 
## HR3 Groups teams comparison [/hr3/groups/{group_id}/teams/comparison]

### Get the list teams for comparison. [GET]
Get result data for list of teams for comparison. Teams are selected by user in group detail.


+ Request (application/json)

    + Headers

            X-Auth-token: your_token
            Accept: application/json
            
    + Body
    
            { "team_ids":[2,5] }


+ Response 200 (application/json)

    + Body
 
            [
               {
            "team":{"id":2,"name":"IT department", "persons": [2,4,8, 11]},
            "1":{"description":["model1_i18nkey","model2_i18nkey"]},
            "2":{"description":["assigment1_i18nkey","assigment2_i18nkey"]},
            "230":{"value":90,"description":["trait1_text1_i18nkey","trait1_text2_i18nkey"],"color":"GREEN","warning":true},
            "112":{"value":15,"description":["trait2_text3_i18nkey"],"color":"RED","warning":false},
            "149":{"value":55,"description":["trait3_text3_i18nkey"],"color":"GREEN","warning":false},
            "240":{"value":65,"description":["trait4_text3_i18nkey"],"color":"GREEN","warning":false},
            "121":{"value":45,"description":["trait5_text3_i18nkey"],"color":"GREEN"},
            "229":{"value":35,"description":["trait6_text3_i18nkey"],"color":"YELLOW"},
            "104":{"value":20,"description":["trait7_text3_i18nkey"],"color":"YELLOW"},
            "226":{"value":5,"description":["trait8_text3_i18nkey"],"color":"RED"},
            "132":{"value":100,"description":["trait9_text3_i18nkey","trait9_text4_i18nkey"],"color":"GREEN","warning":true},
            "130":{"value":0,"description":["trait10_text3_i18nkey"],"color":"RED"},
            "170":{"value":68,"description":["trait11_text3_i18nkey"],"color":"GREEN"},
            "136":{"value":55,"description":["trait12_text3_i18nkey"],"color":"GREEN"},
            "119":{"value":35,"description":["trait13_text3_i18nkey"],"color":"YELLOW"},
            "239":{"value":40,"description":["trait14_text3_i18nkey"],"color":"YELLOW"},
            "143":{"value":73,"description":["trait15_text3_i18nkey"],"color":"GREEN"},
            "148":{"value":67,"description":["trait16_text3_i18nkey"],"color":"GREEN"},
            "234":{"value":73,"description":["trait17_text3_i18nkey"],"color":"GREEN"},
            "164":{"value":84,"description":["trait18_text3_i18nkey","trait18_text1_i18nkey"],"color":"GREEN","warning":true},
            "160":{"value":73,"description":["trait19_text3_i18nkey"],"color":"GREEN"},
            "127":{"value":100,"description":["trait20_text3_i18nkey","trait20_text1_i18nkey"],"color":"GREEN","warning":true},
            "235":[{"name":"role1_name_i18nkey","description":["role1_text1_i18nkey"]},
                {"name":"role2_name_i18nkey","description":["role2_text1_i18nkey"]},
                {"name":"role3_name_i18nkey","description":["role3_text1_i18nkey"]}],
            "237":{"description":["assigment2_i18nkey"]},
            "236":{"description":["model1_i18nkey"]} 
 
            },
            {
             "team":{"id":5,"name":"Management", "persons": [2,4,14,19]},
            "1":{"description":["model1_i18nkey","model2_i18nkey"]},
            "2":{"description":["assigment1_i18nkey","assigment2_i18nkey"]},
            "230":{"value":90,"description":["trait1_text1_i18nkey","trait1_text2_i18nkey"],"color":"GREEN","warning":true},
            "112":{"value":15,"description":["trait2_text3_i18nkey"],"color":"RED","warning":false},
            "149":{"value":55,"description":["trait3_text3_i18nkey"],"color":"GREEN","warning":false},
            "240":{"value":65,"description":["trait4_text3_i18nkey"],"color":"GREEN","warning":false},
            "121":{"value":45,"description":["trait5_text3_i18nkey"],"color":"GREEN"},
            "229":{"value":35,"description":["trait6_text3_i18nkey"],"color":"YELLOW"},
            "104":{"value":20,"description":["trait7_text3_i18nkey"],"color":"YELLOW"},
            "226":{"value":5,"description":["trait8_text3_i18nkey"],"color":"RED"},
            "132":{"value":100,"description":["trait9_text3_i18nkey","trait9_text4_i18nkey"],"color":"GREEN","warning":true},
            "130":{"value":0,"description":["trait10_text3_i18nkey"],"color":"RED"},
            "170":{"value":68,"description":["trait11_text3_i18nkey"],"color":"GREEN"},
            "136":{"value":55,"description":["trait12_text3_i18nkey"],"color":"GREEN"},
            "119":{"value":35,"description":["trait13_text3_i18nkey"],"color":"YELLOW"},
            "239":{"value":40,"description":["trait14_text3_i18nkey"],"color":"YELLOW"},
            "143":{"value":73,"description":["trait15_text3_i18nkey"],"color":"GREEN"},
            "148":{"value":67,"description":["trait16_text3_i18nkey"],"color":"GREEN"},
            "234":{"value":73,"description":["trait17_text3_i18nkey"],"color":"GREEN"},
            "164":{"value":84,"description":["trait18_text3_i18nkey","trait18_text1_i18nkey"],"color":"GREEN","warning":true},
            "160":{"value":73,"description":["trait19_text3_i18nkey"],"color":"GREEN"},
            "127":{"value":100,"description":["trait20_text3_i18nkey","trait20_text1_i18nkey"],"color":"GREEN","warning":true},
            "235":[{"name":"role1_name_i18nkey","description":["role1_text1_i18nkey"]},
                {"name":"role2_name_i18nkey","description":["role2_text1_i18nkey"]},
                {"name":"role3_name_i18nkey","description":["role3_text1_i18nkey"]}],
            "237":{"description":["assigment2_i18nkey"]},
            "236":{"description":["model1_i18nkey"]} 
            }
            
            ]
            
+ Response 400 (application/json)

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageGroupsTeamComparison","type":"error"}
                 ]
            } 

 
### Generate new team result for team comparison [PUT]
Generate new team result, from list of group persons ids.

+ Request (application/json)

    + Headers
    
            X-Auth-token: your_token
            Accept: application/json
            Access-Control-Allow-Origin: *

    + Body
             
            { "persons_ids":[2,5,8,13,24] }
             

+ Response 200  (application/json)

    + Headers
    
            X-License-Hr3: true
            Access-Control-Expose-Headers: X-License-Hr3
    
    + Body
 
            {
            "team":{"id":2,"name":"IT department", "persons": [2,4,8, 11]},
            "1":{"description":["model1_i18nkey","model2_i18nkey"]},
            "2":{"description":["assigment1_i18nkey","assigment2_i18nkey"]},
            "230":{"value":90,"description":["trait1_text1_i18nkey","trait1_text2_i18nkey"],"color":"GREEN","warning":true},
            "112":{"value":15,"description":["trait2_text3_i18nkey"],"color":"RED","warning":false},
            "149":{"value":55,"description":["trait3_text3_i18nkey"],"color":"GREEN","warning":false},
            "240":{"value":65,"description":["trait4_text3_i18nkey"],"color":"GREEN","warning":false},
            "121":{"value":45,"description":["trait5_text3_i18nkey"],"color":"GREEN"},
            "229":{"value":35,"description":["trait6_text3_i18nkey"],"color":"YELLOW"},
            "104":{"value":20,"description":["trait7_text3_i18nkey"],"color":"YELLOW"},
            "226":{"value":5,"description":["trait8_text3_i18nkey"],"color":"RED"},
            "132":{"value":100,"description":["trait9_text3_i18nkey","trait9_text4_i18nkey"],"color":"GREEN","warning":true},
            "130":{"value":0,"description":["trait10_text3_i18nkey"],"color":"RED"},
            "170":{"value":68,"description":["trait11_text3_i18nkey"],"color":"GREEN"},
            "136":{"value":55,"description":["trait12_text3_i18nkey"],"color":"GREEN"},
            "119":{"value":35,"description":["trait13_text3_i18nkey"],"color":"YELLOW"},
            "239":{"value":40,"description":["trait14_text3_i18nkey"],"color":"YELLOW"},
            "143":{"value":73,"description":["trait15_text3_i18nkey"],"color":"GREEN"},
            "148":{"value":67,"description":["trait16_text3_i18nkey"],"color":"GREEN"},
            "234":{"value":73,"description":["trait17_text3_i18nkey"],"color":"GREEN"},
            "164":{"value":84,"description":["trait18_text3_i18nkey","trait18_text1_i18nkey"],"color":"GREEN","warning":true},
            "160":{"value":73,"description":["trait19_text3_i18nkey"],"color":"GREEN"},
            "127":{"value":100,"description":["trait20_text3_i18nkey","trait20_text1_i18nkey"],"color":"GREEN","warning":true},
            "235":[{"name":"role1_name_i18nkey","description":["role1_text1_i18nkey"]},
                {"name":"role2_name_i18nkey","description":["role2_text1_i18nkey"]},
                {"name":"role3_name_i18nkey","description":["role3_text1_i18nkey"]}],
            "237":{"description":["assigment2_i18nkey"]},
            "236":{"description":["model1_i18nkey"]} 
            }
    
+  Response 400 (application/json)

    + Body

            {
                 "messages": [
                    {"i18nKey":"i18nKeyErrorMessageGroupsCreateTeamResult","type":"error"}
                 ]
            } 

 
 
 
 